### ISSUE TITLE
Adicionar Parametros do XTesta

### ISSUE THREAD

**Issue by PauloLuan** [pedro-hos/temis#19]
Atualmente a aplicação nao extrai a descrição resumida da lei, que se encontra no terceiro parâmetro em uma função chamada XTesta (conforme crawler que eu fiz no passado https://github.com/sjcdigital/sjc_laws/blob/master/crawler.js#L64) 

Temos que mudar o seguinte texto que aparece na listagem gerais das leis: "LEI MUNICIPAL Nº 8.911, DE 08/03/2013 - Pub. Boletim nº 2116, de 08/03/2013 - Legislação Municipal Consolidada - Consolidação de Legislação Municipal" pois isto está aparecendo pra todas as leis

E colocar esta descrição resumida no lugar deste texto genérico.

**Comment by pedro-hos** [comment]
@PauloLuan  Legal, a versão da que esta na minha máquina esta fazendo isso. Vou subir isso hoje! Estou pegando o resumo das leis. ;)

**Comment by PauloLuan** [comment]
Show de bola!
